const field = document.getElementById('field');

function show_image(src, coor_y, coor_x) {
    let img = document.createElement("img");
    img.src = src;
    img.style.position = "absolute";
    img.style.width = '100px';
    img.style.left = (coor_x - 50) + 'px';
    img.style.top = (coor_y - 60) + 'px';
    // This next line will just add it to the <body> tag
    field.appendChild(img);
}

field.onclick = (event) => {
    const source_files = [
        'adobe.svg',
        'AdobeIllustrator.svg',
        'AdobePhotoshop.svg',
        'AdobeXD.svg',
        'ae.svg',
        'affinity.svg',
        'affinitydesigner.svg',
        'affinityphoto.svg',
        'affinitypublisher.svg',
        'ai.svg',
        'Aim.svg',
        'Airbnb.svg',
        'airtable.svg',
        'alacritty.svg',
        'algolia.svg',
        'algorand.svg',
        'alpinejs.svg',
        'Amazon.svg',
        'amp.svg',
        'amznwebserv.svg',
        'analytics.svg',
        'android.svg',
        'angular.svg',
        'angular17.svg',
        'antd.svg',
        'apache.svg',
        'Apple.svg',
        'AppStore.svg',
        'appwrite.svg',
        'arc.svg',
        'Asana.svg',
        'astro.svg',
        'atlassian.svg',
        'atom.svg',
        'auth0.svg',
        'avajs.svg',
        'aws.svg',
        'axiom.svg',
        'axm.svg',
        'axure.svg',
        'azure.svg',
        'babel.svg',
        'backbonejs.svg',
        'Badoo.svg',
        'Basecamp.svg',
        'bash.svg',
        'Behance.svg',
        'Binance.svg',
        'Bing.svg',
        'bitbucket.svg',
        'Bitcoin.svg',
        'bitnami.svg',
        'Bittorrent.svg',
        'Blogger.svg',
        'blueprintjs.svg',
        'bootstrap4.svg',
        'bootstrap5.svg',
        'brave.svg',
        'Buffer.svg',
        'bulmaui.svg',
        'bunjs.svg',
        'BuzzFeed.svg',
        'c++.svg',
        'cakephp.svg',
        'canva.svg',
        'cassandradb.svg',
        'chakraui.svg',
        'chrome.svg',
        'chromium.svg',
        'circleci.svg',
        'clickhouse.svg',
        'clojure.svg',
        'cloudflare.svg',
        'cloudinary.svg',
        'codefresh.svg',
        'codeigniter.svg',
        'Codeopen.svg',
        'Coinbase.svg',
        'Confluence.svg',
        'Cool Shape-1.svg',
        'Cool Shape-10.svg',
        'Cool Shape-100.svg',
        'Cool Shape-101.svg',
        'Cool Shape-102.svg',
        'Cool Shape-103.svg',
        'Cool Shape-104.svg',
        'Cool Shape-105.svg',
        'Cool Shape-106.svg',
        'Cool Shape-107.svg',
        'Cool Shape-108.svg',
        'Cool Shape-109.svg',
        'Cool Shape-11.svg',
        'Cool Shape-110.svg',
        'Cool Shape-111.svg',
        'Cool Shape-112.svg',
        'Cool Shape-113.svg',
        'Cool Shape-114.svg',
        'Cool Shape-12.svg',
        'Cool Shape-13.svg',
        'Cool Shape-14.svg',
        'Cool Shape-15.svg',
        'Cool Shape-16.svg',
        'Cool Shape-17.svg',
        'Cool Shape-18.svg',
        'Cool Shape-19.svg',
        'Cool Shape-2.svg',
        'Cool Shape-20.svg',
        'Cool Shape-21.svg',
        'Cool Shape-22.svg',
        'Cool Shape-23.svg',
        'Cool Shape-24.svg',
        'Cool Shape-25.svg',
        'Cool Shape-26.svg',
        'Cool Shape-27.svg',
        'Cool Shape-28.svg',
        'Cool Shape-29.svg',
        'Cool Shape-3.svg',
        'Cool Shape-30.svg',
        'Cool Shape-31.svg',
        'Cool Shape-32.svg',
        'Cool Shape-33.svg',
        'Cool Shape-34.svg',
        'Cool Shape-35.svg',
        'Cool Shape-36.svg',
        'Cool Shape-37.svg',
        'Cool Shape-38.svg',
        'Cool Shape-39.svg',
        'Cool Shape-4.svg',
        'Cool Shape-40.svg',
        'Cool Shape-41.svg',
        'Cool Shape-42.svg',
        'Cool Shape-43.svg',
        'Cool Shape-44.svg',
        'Cool Shape-45.svg',
        'Cool Shape-46.svg',
        'Cool Shape-47.svg',
        'Cool Shape-48.svg',
        'Cool Shape-49.svg',
        'Cool Shape-5.svg',
        'Cool Shape-50.svg',
        'Cool Shape-51.svg',
        'Cool Shape-52.svg',
        'Cool Shape-53.svg',
        'Cool Shape-54.svg',
        'Cool Shape-55.svg',
        'Cool Shape-56.svg',
        'Cool Shape-57.svg',
        'Cool Shape-58.svg',
        'Cool Shape-59.svg',
        'Cool Shape-6.svg',
        'Cool Shape-60.svg',
        'Cool Shape-61.svg',
        'Cool Shape-62.svg',
        'Cool Shape-63.svg',
        'Cool Shape-64.svg',
        'Cool Shape-65.svg',
        'Cool Shape-66.svg',
        'Cool Shape-67.svg',
        'Cool Shape-68.svg',
        'Cool Shape-69.svg',
        'Cool Shape-7.svg',
        'Cool Shape-70.svg',
        'Cool Shape-71.svg',
        'Cool Shape-72.svg',
        'Cool Shape-73.svg',
        'Cool Shape-74.svg',
        'Cool Shape-75.svg',
        'Cool Shape-76.svg',
        'Cool Shape-77.svg',
        'Cool Shape-78.svg',
        'Cool Shape-79.svg',
        'Cool Shape-8.svg',
        'Cool Shape-80.svg',
        'Cool Shape-81.svg',
        'Cool Shape-82.svg',
        'Cool Shape-83.svg',
        'Cool Shape-84.svg',
        'Cool Shape-85.svg',
        'Cool Shape-86.svg',
        'Cool Shape-87.svg',
        'Cool Shape-88.svg',
        'Cool Shape-89.svg',
        'Cool Shape-9.svg',
        'Cool Shape-90.svg',
        'Cool Shape-91.svg',
        'Cool Shape-92.svg',
        'Cool Shape-93.svg',
        'Cool Shape-94.svg',
        'Cool Shape-95.svg',
        'Cool Shape-96.svg',
        'Cool Shape-97.svg',
        'Cool Shape-98.svg',
        'Cool Shape-99.svg',
        'Cool Shape.svg',
        'copilotgithub.svg',
        'copilotms.svg',
        'Coub.svg',
        'Creativemarket.svg',
        'crystal.svg',
        'csharp.svg',
        'css3.svg',
        'cypress.svg',
        'Dailymotion.svg',
        'dart.svg',
        'datadog.svg',
        'deno.svg',
        'Digg.svg',
        'digitalocean.svg',
        'Discord.svg',
        'django.svg',
        'dlang.svg',
        'docker.svg',
        'docusaurus.svg',
        'dovetail.svg',
        'Dribbble.svg',
        'Dropbox.svg',
        'Drupal.svg',
        'DuckDuckGo.svg',
        'ec2.svg',
        'edge.svg',
        'elastic.svg',
        'electron.svg',
        'elementui.svg',
        'elixir.svg',
        'ember.svg',
        'Epic Games.svg',
        'erlang.svg',
        'esbuild.svg',
        'eslint.svg',
        'Ethereum.svg',
        'Evernote.svg',
        'ExpressVPN.svg',
        'Facebook.svg',
        'Fancy.svg',
        'faunadb.svg',
        'figma.svg',
        'firebase.svg',
        'firefox.svg',
        'flask.svg',
        'Flickr.svg',
        'flutter.svg',
        'flyio.svg',
        'Foursquare.svg',
        'framer.svg',
        'gatsby.svg',
        'gcloud.svg',
        'git.svg',
        'github.svg',
        'gitlab.svg',
        'Gmail.svg',
        'go.svg',
        'Google Calendar.svg',
        'Google Chrome.svg',
        'Google Docs.svg',
        'Google Drive.svg',
        'Google Meet.svg',
        'Google.svg',
        'GooglePlay.svg',
        'grafana.svg',
        'grafbase.svg',
        'graphite.svg',
        'graphql.svg',
        'gridsome.svg',
        'gruntjs.svg',
        'gulp.svg',
        'Gumroad.svg',
        'haskell.svg',
        'headlessui.svg',
        'heroku.svg',
        'hexo.svg',
        'hhvm.svg',
        'Hola.svg',
        'homebrew.svg',
        'hotjar.svg',
        'html5.svg',
        'hyper.svg',
        'hyper2.svg',
        'i18next.svg',
        'Iconfinder.svg',
        'Iconjar.svg',
        'id.svg',
        'ie.svg',
        'inkspace.svg',
        'insomnia.svg',
        'Instagram.svg',
        'Intercom.svg',
        'invision.svg',
        'ionic.svg',
        'jamstack.svg',
        'java.svg',
        'jest.svg',
        'jira.svg',
        'jquery.svg',
        'js.svg',
        'jslint.svg',
        'json.svg',
        'Kaixin001.svg',
        'KakaoTalk.svg',
        'kibana.svg',
        'Kickstarter.svg',
        'kotlin.svg',
        'kubernetes.svg',
        'laravel.svg',
        'less.svg',
        'lightroom.svg',
        'Line.svg',
        'LinkedIn.svg',
        'linux.svg',
        'lit.svg',
        'liveblocks.svg',
        'logrocket.svg',
        'lokalise.svg',
        'lua.svg',
        'lunacy.svg',
        'Mail_ru.svg',
        'MailChimp.svg',
        'mariadb.svg',
        'marionette.svg',
        'markdown.svg',
        'Marvel.svg',
        'Mastercard.svg',
        'materialui.svg',
        'Medium.svg',
        'Mega.svg',
        'Messenger.svg',
        'meta.svg',
        'MetaMask.svg',
        'Mi.svg',
        'Microsoft Excel.svg',
        'Microsoft Word.svg',
        'microsoft.svg',
        'Miliao.svg',
        'miro.svg',
        'mochajs.svg',
        'mongodb.svg',
        'mozilla.svg',
        'mysql.svg',
        'neovim.svg',
        'nestjs.svg',
        'Netflix.svg',
        'netlify.svg',
        'netlify2.svg',
        'nextjs.svg',
        'nextjs2.svg',
        'nim.svg',
        'Nintendo.svg',
        'nitro.svg',
        'nodejs.svg',
        'NordVPN .svg',
        'Notion.svg',
        'npm.svg',
        'npm2.svg',
        'nuxtjs.svg',
        'ocaml.svg',
        'OK.svg',
        'onedrive.svg',
        'openai.svg',
        'opera.svg',
        'oracle.svg',
        'Outlook.svg',
        'pandacss.svg',
        'Patreon.svg',
        'Payoneer.svg',
        'PayPal.svg',
        'Periscope.svg',
        'php.svg',
        'pinia.svg',
        'Pinterest.svg',
        'pixijs.svg',
        'Playstation.svg',
        'playwright.svg',
        'Pocket.svg',
        'postgresql.svg',
        'postman.svg',
        'powershell.svg',
        'preact.svg',
        'presto.svg',
        'prettier.svg',
        'prisma.svg',
        'ProductHunt.svg',
        'ps.svg',
        'pugjs.svg',
        'pwa.svg',
        'python.svg',
        'pytorch.svg',
        'pytorch3d.svg',
        'QQ.svg',
        'Quora.svg',
        'qwik.svg',
        'radixui.svg',
        'rails.svg',
        'railway.svg',
        'reactjs.svg',
        'reactquery.svg',
        'reactrouter.svg',
        'Reddit.svg',
        'redhat.svg',
        'redis.svg',
        'redux.svg',
        'reduxsaga.svg',
        'render.svg',
        'Renren.svg',
        'resend.svg',
        'rollup.svg',
        'RSS.svg',
        'ruby.svg',
        'rust.svg',
        'safari.svg',
        'sass.svg',
        'scala.svg',
        'semanticui.svg',
        'serverless.svg',
        'shadcnui.svg',
        'Shopify.svg',
        'Shutterstock.svg',
        'Signal.svg',
        'sketch.svg',
        'sketch2.svg',
        'Skrill.svg',
        'Skype.svg',
        'slack.svg',
        'Snapchat.svg',
        'solidity.svg',
        'solidjs.svg',
        'Spotify.svg',
        'spring.svg',
        'Steam.svg',
        'storyblok.svg',
        'storybook.svg',
        'strada.svg',
        'Strava.svg',
        'stream.svg',
        'StumbleUpon.svg',
        'stylelint.svg',
        'sublime.svg',
        'supabase.svg',
        'sveltejs.svg',
        'swagger.svg',
        'swift.svg',
        'tailwindcss.svg',
        'Taobao.svg',
        'TeamViewer.svg',
        'Telegram.svg',
        'Tether.svg',
        'threejs.svg',
        'Tidal.svg',
        'Tik Tok.svg',
        'Tilda.svg',
        'Tinder.svg',
        'tinyhttp.svg',
        'Tor.svg',
        'Treehouse.svg',
        'Trello.svg',
        'Tripadvisor.svg',
        'tRPC.svg',
        'Tumblr.svg',
        'Tux.svg',
        'Twitch.svg',
        'Twitter.svg',
        'typescript.svg',
        'ubuntu.svg',
        'ui8.svg',
        'unjs.svg',
        'Uplabs.svg',
        'ur.svg',
        'Utorrent.svg',
        'Viadeo.svg',
        'Viber.svg',
        'vim.svg',
        'Vimeo.svg',
        'Vine.svg',
        'Visa.svg',
        'visualbasic.svg',
        'vitejs.svg',
        'vitest.svg',
        'VK.svg',
        'vscode.svg',
        'vuejs.svg',
        'webassembly.svg',
        'webpack.svg',
        'Wechat.svg',
        'Weibo.svg',
        'WhatsApp Business.svg',
        'WhatsApp.svg',
        'Wickr.svg',
        'Wikipedia.svg',
        'Windows.svg',
        'Wire.svg',
        'wordpress.svg',
        'xamarin.svg',
        'Xbox.svg',
        'xd.svg',
        'YandexBrowser.svg',
        'Yelp.svg',
        'yoga.svg',
        'Youtube.svg',
        'Zendesk.svg',
        'Zerpply.svg',
        'zod.svg',
        'Zoom.svg',
    ];
    random_number = Math.floor(Math.random() * source_files.length);
    show_image('img/' + source_files[random_number], event.clientY, event.clientX);
}